steps:
- name: 'us-central1-docker.pkg.dev/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/simple-app:${_VERSION}', '.']
- name: 'us-central1-docker.pkg.dev/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/simple-app:${_VERSION}']
images: ['us-central1-docker.pkg.dev/$PROJECT_ID/simple-app:${_VERSION}']